return {
    AlreadyStarted = "Framework has already started",
	NotStarted = "Framework has not started yet",
	CannotInit = "Init errored; '%s'",
	CannotStart = "Start errored; '%s'",
    CannotLoad = "Load errored; '%s'",
	IncorrectType = "Item '%s' is the incorrect type; expects %s",
	IncorrectContext = "Using parameter %s on the incorrect context",
	MustProvide = "Must provide a %s",
	ItemNotOptional = "Item '%s' is not optional and must be included",
	ItemNotFound = "Item '%s' could not be found as a valid item",
}
